const mongoose = require("mongoose");
const { Schema } = mongoose;

/**
 * SCHEMA DOCS GENERATED BY GPT-4o ON FEB-05-2026. USE WITH CAUTION.
 * Schema definition for a Squid Game player.
 * Represents the structure of a player's data, including personal information,
 * game statuses, and performance in individual games.
 *
 * @typedef {Object} PlayerSchema
 * @property {Object} info - Personal information about the player.
 * @property {string} info.firstName - The player's first name.
 * @property {string} info.lastName - The player's last name.
 * @property {number} info.playerNumber - The unique player number (required).
 * @property {number} info.studentNumber - The unique student number (required).
 * @property {string} info.grade - The grade or level of the player.
 * @property {Object} info.medical - Medical information about the player.
 * @property {boolean} info.medical.needed - Whether medical attention is needed (default: false).
 * @property {string} info.medical.description - Description of medical needs.
 *
 * @property {Object} status - The current status of the player.
 * @property {boolean} status.attendance - Whether the player is present (default: false).
 * @property {boolean} status.eliminated - Whether the player is eliminated (default: false).
 * @property {string} status.eliminatedBy - The entity that eliminated the player.
 * @property {number} status.eliminatedAt - The timestamp of elimination.
 * @property {string} status.eliminatedIn - The game in which the player was eliminated.
 * @property {string} status.location - The current location of the player.
 *
 * @property {Object} games - Performance data for individual games.
 * @property {Object} games.redLightGreenLight - Data for the "Red Light, Green Light" game.
 * @property {number} games.redLightGreenLight.timeSpent - Time spent in the game.
 * @property {number} games.redLightGreenLight.passes - Number of successful passes (default: 0).
 * @property {boolean} games.redLightGreenLight.eliminated - Whether the player was eliminated (default: false).
 * @property {Object} games.dalgona - Data for the "Dalgona" game.
 * @property {string} games.dalgona.shape - The shape assigned to the player.
 * @property {number} games.dalgona.timeSpent - Time spent in the game.
 * @property {boolean} games.dalgona.eliminated - Whether the player was eliminated (default: false).
 * @property {Object} games.tugOfWar - Data for the "Tug of War" game.
 * @property {number} games.tugOfWar.team - The team number assigned to the player.
 * @property {boolean} games.tugOfWar.eliminated - Whether the player was eliminated (default: false).
 * @property {Object} games.mingle - Data for the "Mingle" game.
 * @property {number} games.mingle.timeAlive - Time the player stayed alive in the game.
 * @property {boolean} games.mingle.eliminated - Whether the player was eliminated (default: false).
 */

const playerSchema = new Schema({
    info: {
        firstName: String,
        lastName: String,
        playerNumber: { type: Number, required: true, unique: true },
        studentNumber: { type: Number, required: true, unique: true },
        grade: String,
        medical: {
            needed: { type: Boolean, required: true, default: false },
            description: String,
        },
    },
    status: {
        attendance: { type: Boolean, required: true, default: false },
        eliminated: { type: Boolean, required: true, default: false },
        eliminatedBy: String,
        eliminatedAt: Number,
        eliminatedIn: String,
        location: String,
    },
    games: {
        redLightGreenLight: {
            timeAlive: Number,
            passes: { type: Number, required: true, default: 0 },
            eliminated: { type: Boolean, required: true, default: false },
        },
        dalgona: {
            shape: String,
            timeSpent: Number,
            eliminated: { type: Boolean, required: true, default: false },
        },
        tugOfWar: {
            team: Number,
            eliminated: { type: Boolean, required: true, default: false },
        },
        mingle: {
            timeAlive: Number,
            eliminated: { type: Boolean, required: true, default: false },
        },
    },
});

const guardSchema = new Schema({
	firstName: String,
	lastName: String,
	organization: String,
	studentNumber: {
		type: Number,
		required: true,
		unique: true,
	},
	grade: Number,
	guardId: {
		type: Number,
		required: true,
		unique: true,
	},
    discordId: {
        type: String,
        required: true,
        unique: true,
    }
});

const GameSchema = new Schema({
    active: { type: Boolean, required: true, default: false },
    game: String,
    redLightGreenLight: {
        startTime: Number,
    },
    dalgona: {
        startTime: Number,
    },
    tugOfWar: {
        startTime: Number,
    },
    mingle: {
        startTime: Number,
    },
});

const Player = mongoose.model("Player", playerSchema);
const Guard = mongoose.model("Guard", guardSchema);
const Game = mongoose.model("Game", GameSchema);
module.exports = { Player, Guard, Game };